spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5435/documentdb
    username: document_user
    password: T0byt081*
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
