apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-pvc
  namespace: facturacion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: facturacion
spec:
  replicas: 1
  strategy:
    type: Recreate   # evita 2 Pods de Postgres montando el mismo PVC a la vez
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: auth-db-credentials, key: username }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: auth-db-credentials, key: password }
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef: { name: auth-db-credentials, key: database }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: auth-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: facturacion
spec:
  selector:
    app: auth-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
